# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.AlterField(
            model_name='reply',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
