# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-22 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190821_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
